# Serve Settings
timezone: America/New_York

# Site Settings
title: Joanna Shea O'Brien
subtitle: Oral History, Research and Writing
email: jsheaobrien@gmail.com
# description: If I had a description it would go here.
#baseurl: ""
#url: ""
twitter_username: jsheaobrien
linkedin_username: joanna-shea-o-brien-a79b8b54
instagram_username: jsheaobrien

# Build Settings
markdown: kramdown

# Pluggins
plugins:
 - jekyll-coffeescript

sass:
  sass_dir: assets/css

exclude:
 - README.md
 - *.psd
